### ISSUE TITLE
Add some screenshots to attract more people

### ISSUE THREAD

**Issue by RealTheHexagon** [vicr123/thedesk#5]
I feel like you should add more screenshots to attract people, because theDesk takes a while to build, so they don't have to wait a while to find a DE they don't like, and that they don't go in blind.

**Comment by krak3n77** [comment]
+1 This

**Comment by melted349** [comment]
+1 This

**Comment by lucas-gio** [comment]
Hahah, this was my reaction when i navigate across readme of this project. The main part ¿where?. The screenshots are main for this type of projects.
