### ISSUE TITLE
Cant install/build thedesk (Fixed)

### ISSUE THREAD

**Issue by Markynose** [vicr123/thedesk#9]
![Знімок екрана з 2023-11-04 08-44-00](https://github.com/theCheeseboard/thedesk/assets/135860662/a7b14808-9365-4b2e-95c1-69b025b19440)
How to fix this?
Error 3 at the end
cant install libthedesk

**Comment by Markynose** [comment]
Im using crystal linux(arch linux)

**Comment by vicr123** [comment]
Hi, please use CMake and ensure that you have all the dependencies installed. You will require the unstable version of KDE Frameworks 6 (networkmanager-qt, modemmanager-qt and pulseaudio-qt) as well.

**Comment by Markynose** [comment]
![Знімок екрану_2023-11-04_18-23-05](https://github.com/theCheeseboard/thedesk/assets/135860662/0f077025-0281-4116-87cb-1aae3e01387c)
have cmake but these dependencies wont build

**Comment by Markynose** [comment]
https://github.com/theCheeseboard/thedesk/assets/135860662/5a21d9ed-8469-47d3-9d5f-d11351056af5

Here's a video how it installs/builds

**Comment by Markynose** [comment]
@vicr123 I will Close this issue for a day

**Comment by Markynose** [comment]
Thedesk won't build/install even on arch and Fedora☹️

**Comment by vicr123** [comment]
Hey mate, theDesk currently relies on KDE Frameworks 6 which is not yet released. You may have to try building that from source or see if an unstable repository is available for your system with the required packages.

**Comment by Markynose** [comment]
@vicr123 Yo mate, long time no see actually i download kde framework 6 everything works normal, thanks!

**Comment by Markynose** [comment]
@vicr123 🙏 help pls
![Screenshot_20231224_182847](https://github.com/theCheeseboard/thedesk/assets/135860662/62b1fb2d-6b90-46c2-ab4c-2189bfd21d7b)

**Comment by Markynose** [comment]
> Hey mate, theDesk currently relies on KDE Frameworks 6 which is not yet released. You may have to try building that from source or see if an unstable repository is available for your system with the required packages.

also i have unstable kde repo
![Screenshot_20231224_183311](https://github.com/theCheeseboard/thedesk/assets/135860662/1a9cb948-8bf8-4ec1-b253-9734e5ee093e)

**Comment by vicr123** [comment]
I haven't updated the packages to work with the KDE unstable repo yet. I'll let you know when the AUR package is fixed.

**Comment by Markynose** [comment]
> I haven't updated the packages to work with the KDE unstable repo yet. I'll let you know when the AUR package is fixed.

OK, thanks, bro😉

**Comment by Markynose** [comment]
> I haven't updated the packages to work with the KDE unstable repo yet. I'll let you know when the AUR package is fixed.

Yo Hi, so u updated the packages or what?

**Comment by vicr123** [comment]
Plasma 6 is coming out this month, so I'll wait for the packages to hit the stable repository. Shouldn't be too long now.

**Comment by Markynose** [comment]
> Plasma 6 is coming out this month, so I'll wait for the packages to hit the stable repository. Shouldn't be too long now.

OK, Thanks for the reply :)

**Comment by Markynose** [comment]
Hi again! So how is KDE framework 6? Is it out?

**Comment by vicr123** [comment]
Hi, KDE 6 is released now. I'm waiting for the Arch folks to package it and release it into the repositories.

**Comment by Markynose** [comment]
:D
